DROP DATABASE IF EXISTS Subscription;
CREATE DATABASE Subscription;
USE Subscription;

DROP TABLE IF EXISTS Parents;
CREATE TABLE Parents (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Phone VARCHAR(20) NOT NULL UNIQUE KEY,
    Email VARCHAR(100) NOT NULL UNIQUE KEY
);

DROP TABLE IF EXISTS Students;
CREATE TABLE Students (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Dob DATE NOT NULL,
    Gender ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL,
    Current_grade VARCHAR(20) NOT NULL,
    Parent_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (Parent_id) REFERENCES Parents(Id)
);

DROP TABLE IF EXISTS Classes;
CREATE TABLE Classes (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Subject VARCHAR(50) NOT NULL,
    Day_of_week ENUM('MON','TUE','WED','THU','FRI','SAT','SUN') NOT NULL,
    Time_slot VARCHAR(50) NOT NULL,
    Teacher_name VARCHAR(100) NOT NULL,
    Max_students INT UNSIGNED NOT NULL
);

DROP TABLE IF EXISTS Class_registrations;
CREATE TABLE Class_registrations (
    Class_id INT UNSIGNED NOT NULL,
    Student_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (Class_id, Student_id),
    FOREIGN KEY (Class_id) REFERENCES Classes(Id),
    FOREIGN KEY (Student_id) REFERENCES Students(Id)
);

DROP TABLE IF EXISTS Subscriptions;
CREATE TABLE Subscriptions (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Student_id INT UNSIGNED NOT NULL,
    Package_name VARCHAR(100) NOT NULL,
    Start_date DATE NOT NULL,
    End_date DATE NOT NULL,
    Total_sessions INT NOT NULL,
    Used_sessions INT DEFAULT 0 NOT NULL,
    FOREIGN KEY (Student_id) REFERENCES Students(id)
);